### ISSUE TITLE
crash if LANG not set

### ISSUE THREAD

**Issue by 6543** [nwg-piotr/nwg-displays#18]
workaround:

start with:
`LANG=en_US nwg-displays`

**Comment by nwg-piotr** [comment]
Could you show the crash in terminal output?  With such amount of info, I can only say: "It works for me". Also please provide your `printenv` output.

**Comment by 6543** [comment]
well it was easier to just make a patch  #19 ;)

**Comment by nwg-piotr** [comment]
OK
