### ISSUE TITLE
Popup + countdown to prevent incorrect configuration

### ISSUE THREAD

**Issue by hakan-demirli** [nwg-piotr/nwg-displays#31]
I accidentally changed my refresh rate to 59 instead of 60. My monitor instantly turned dark and I had to manually fix it via tty login.

Other display tools such as gnome, kde and Windows Display Settings offer a countdown mechanism that resets the display settings after 20 seconds if the user do not press apply again. Can you add such a feature to nwg-displays?

**Comment by nwg-piotr** [comment]
Yes, it could be done. I'll try in the nearest future.

**Comment by nwg-piotr** [comment]
This is not as easy as one could expect. I'm testing on Hyprland, and some settings (improper refresh rate) just crash the compositor, together with my program, of course. No chance to restore anything. So this will be a half-way solution.

**Comment by hakan-demirli** [comment]
I have found a related problem https://github.com/hyprwm/Hyprland/issues/3083 they mention it being a wlroots bug. 

In one of the issues mentioned, they say Hyprland using a slightly old wlroots version. I think the crash problem will be gone in couple of months after they update their dependencies. If not I will open an another issue over there tagging this one.

**Comment by nwg-piotr** [comment]
Very well. I need to add translations for the new window, then it should be ready.

**Comment by nwg-piotr** [comment]
It seems not to crash on Hyprland 0.30.0.

**Comment by nwg-piotr** [comment]
Done. :rofl: 

![image](https://github.com/nwg-piotr/nwg-displays/assets/20579136/0f604563-c67f-4d20-bf1a-4c4a64e68517)
