### ISSUE TITLE
"Apply" not applying settings

### ISSUE THREAD

**Issue by Rdeisenroth** [nwg-piotr/nwg-displays#34]
Hi, when using Hyprland, the Settings are not applied for me, unless i press keep and manually reload the hyprland config. Is this intended behavior?

**Comment by nwg-piotr** [comment]
No. It should work the same way as on sway. You must have set `disable_autoreload true` in Hyprland settings.

**Comment by Rdeisenroth** [comment]
oh yes indeed, that was the issue.

**Comment by nwg-piotr** [comment]
I thought it was quite obvious, but maybe you're right.
