### ISSUE TITLE
please add auto reload and screen reolution detection is possible

### ISSUE THREAD

**Issue by vs66388** [nwg-piotr/nwg-displays#38]
please add a way that when a the app is run it automatically detects the display and ther the resolution to that  and a nice sclling i mean hyprland default scaling is bad

**Comment by nwg-piotr** [comment]
This is a Hyprland issue, and only appears on some monitors. Please report to the Hyprland issue tracker.

**Comment by nwg-piotr** [comment]
Consider using default settings like this: https://github.com/nwg-piotr/nwg-iso/blob/master/nwglive/airootfs/etc/skel/.config/hypr/monitors.conf

**Comment by nwg-piotr** [comment]
Consider using default config like this: https://github.com/nwg-piotr/nwg-iso/blob/master/nwglive/airootfs/etc/skel/.config/hypr/monitors.conf
