### ISSUE TITLE
Unable to set precise fractional scaling for display

### ISSUE THREAD

**Issue by alanorth** [nwg-piotr/nwg-displays#4]
My sway/kanshi config has each of my displays at a scale factor of 1.33, but when I try to set the same in nwg-displays it reverts to 1.3 when I apply the settings. I'm not sure if it is actually applying the 1.33 scale and rounding down in the UI, or if it's actually unable to use values such as 1.33.

nwg-version 0.1.2.

**Comment by nwg-piotr** [comment]
I didn't expect more than one decimal digits to be necessary. The commit above changes the value to 2.

**Comment by alanorth** [comment]
Ah thank you. Yes I think it's common to use more than one decimal digit. I'll test and let you know. Thank you!

**Comment by alanorth** [comment]
Working great!

**Comment by nwg-piotr** [comment]
Does it affect #3 in any way?
