### ISSUE TITLE
nwg-displays 0.3.10-1 dies in list_outputs when display is disabled

### ISSUE THREAD

**Issue by nergdron** [nwg-piotr/nwg-displays#42]
just trying out nwg on hyprland, and I mostly love it. definitely makes things a lot easier to configure and deal with. however, on my arch install of version 0.3.10-1 of nwg-displays, I disabled a display output (my VR headset, which shouldn't be active all the time), and now nwg-displays just crashes when I try to launch it, so I can't do any further display configuration:

```
Settings: {'view-scale': 0.25, 'snap-threshold': 10, 'indicator-timeout': 500, 'custom-mode': [], 'use-desc': False}
Running on Hyprland
Traceback (most recent call last):
  File "/usr/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.3.10', 'gui_scripts', 'nwg-displays')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 1224, in main
    create_display_buttons()
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 548, in create_display_buttons
    outputs = list_outputs()
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_displays/tools.py", line 186, in list_outputs
    if int(outputs_dict[key]["x"]) == geometry.x and int(outputs_dict[key]["y"]) == geometry.y:
           ~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'x'
```

any theory on what's going on, and how I might modify things so that the VR headset remains disabled but I can still use the app?

**Comment by kRHYME7** [comment]
Got this also, I remembered 
 I disabled the 2nd monitor, then exit the nwg.
Then I remove the monitor. I'm testing which configurations can be retained.
Launch nwg again and give this error.

This might not the specific way to repro this.

I randomly found this issue when a few moments ago I tested nwg and got those errors.

Thank for the hardwork.

**Comment by nwg-piotr** [comment]
Thanks in advance for further info.

**Comment by nergdron** [comment]
for reference, I have 3 display output devices. 2 is my monitor, 3 is the VR headset, and 1 is a home theater receiver via HDMI for audio. I disabled #2, saved, closed `nwg-displays`, and then later tried to open it again to check VRR status on my monitor, and got this error. I've since edited `monitors.conf` by hand to add VRR and 10 bit output, but `nwg-displays` still gives me the error. here's the current contents of my `monitors.conf`:

```
# Generated by nwg-displays on 2023-12-28 at 20:54:52. Do not edit manually.

monitor=HDMI-A-1,1920x1080@60.0,3840x2160,1.0
monitor=DP-2,3840x2160@59.997002,0x0,1.5,bitdepth,10,vrr,1
monitor=DP-3,disable
```

here's the current `wlr-randr` output:

```
DP-2 "LG Electronics LG Ultra HD 0x0004714D (DP-2)"
  Make: LG Electronics
  Model: LG Ultra HD
  Serial: 0x0004714D
  Physical size: 600x340 mm
  Enabled: yes
  Modes:
    3840x2160 px, 59.997002 Hz (preferred, current)
    3840x2160 px, 60.023998 Hz
    3840x2160 px, 50.005001 Hz
    3840x2160 px, 48.006001 Hz
    3840x2160 px, 30.000000 Hz
    2560x1440 px, 59.951000 Hz
    1920x1200 px, 59.997002 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1600x1200 px, 59.997002 Hz
    1680x1050 px, 59.997002 Hz
    1600x900 px, 60.000000 Hz
    1280x1024 px, 60.020000 Hz
    1440x900 px, 59.997002 Hz
    1280x800 px, 59.810001 Hz
    1152x864 px, 59.972000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 60.317001 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.500000
  Adaptive Sync: disabled
DP-3 "(null) (null) (DP-3)"
  Make: (null)
  Model: (null)
  Serial: (null)
  Enabled: no
  Modes:
    640x480 px, 59.939999 Hz
HDMI-A-1 "DENON, Ltd. DENON-AVAMP 0x01010101 (HDMI-A-1)"
  Make: DENON, Ltd.
  Model: DENON-AVAMP
  Serial: 0x01010101
  Physical size: 800x450 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000000 Hz (current)
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 50.000000 Hz
    1920x1080 px, 24.000000 Hz
    1920x1080 px, 23.976000 Hz
    2880x576 px, 50.000000 Hz
    2880x576 px, 50.000000 Hz
    2880x480 px, 60.000000 Hz
    2880x480 px, 60.000000 Hz
    2880x480 px, 59.939999 Hz
    2880x480 px, 59.939999 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 50.000000 Hz
    1280x720 px, 50.000000 Hz
    1440x576 px, 50.000000 Hz
    1440x576 px, 50.000000 Hz
    1440x480 px, 60.000000 Hz
    1440x480 px, 60.000000 Hz
    1440x480 px, 59.939999 Hz
    1440x480 px, 59.939999 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
  Position: 3840,2160
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: enabled
```

**Comment by nergdron** [comment]
I just tried re-enabling `DP-3` in the config file, and once I do, then `nwg-displays` works normally for me again. so it must be something to do with having that display disabled. I've set it and `HDMI-A-1` to mirror the main display so my cursor doesn't go off screen into some void of non-real displays, and that seems like it'll work for now.

for reference, here's the `wlr-randr` output after re-enabling it:

```
DP-3 "(null) (null) (DP-3)"
  Make: (null)
  Model: (null)
  Serial: (null)
  Enabled: yes
  Modes:
    640x480 px, 59.939999 Hz (current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
HDMI-A-1 "DENON, Ltd. DENON-AVAMP 0x01010101 (HDMI-A-1)"
  Make: DENON, Ltd.
  Model: DENON-AVAMP
  Serial: 0x01010101
  Physical size: 800x450 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000000 Hz (current)
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 50.000000 Hz
    1920x1080 px, 24.000000 Hz
    1920x1080 px, 23.976000 Hz
    2880x576 px, 50.000000 Hz
    2880x576 px, 50.000000 Hz
    2880x480 px, 60.000000 Hz
    2880x480 px, 60.000000 Hz
    2880x480 px, 59.939999 Hz
    2880x480 px, 59.939999 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 50.000000 Hz
    1280x720 px, 50.000000 Hz
    1440x576 px, 50.000000 Hz
    1440x576 px, 50.000000 Hz
    1440x480 px, 60.000000 Hz
    1440x480 px, 60.000000 Hz
    1440x480 px, 59.939999 Hz
    1440x480 px, 59.939999 Hz
    720x576 px, 50.000000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: enabled
DP-2 "LG Electronics LG Ultra HD 0x0004714D (DP-2)"
  Make: LG Electronics
  Model: LG Ultra HD
  Serial: 0x0004714D
  Physical size: 600x340 mm
  Enabled: yes
  Modes:
    3840x2160 px, 59.997002 Hz (preferred, current)
    3840x2160 px, 60.023998 Hz
    3840x2160 px, 50.005001 Hz
    3840x2160 px, 48.006001 Hz
    3840x2160 px, 30.000000 Hz
    2560x1440 px, 59.951000 Hz
    1920x1200 px, 59.997002 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1600x1200 px, 59.997002 Hz
    1680x1050 px, 59.997002 Hz
    1600x900 px, 60.000000 Hz
    1280x1024 px, 60.020000 Hz
    1440x900 px, 59.997002 Hz
    1280x800 px, 59.810001 Hz
    1152x864 px, 59.972000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 60.317001 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.500000
  Adaptive Sync: enabled
```

the problem headset in question is a Valve Index, and all the reported nulls in different things are pretty suspicious, so I imagine they might be related to the problems `nwg-displays` is having. it should obviously also be capable of might higher resolutions and refresh rates, so something funky is going on with it under linux. :woman_shrugging:

**Comment by nwg-piotr** [comment]
The crash itself is possible to avoid, but we have another issue: disabled DP monitors disappear from the output of `hyprctl monitors` (why?!), but remain in the output of `wlr-randr` (unfortunately with `Enabled: yes`!). At the same time HDMI outputs once disabled, became invisible to both commands. We no longer detect them in any way. This is most likely a bug in Hyprland, as previously they were still possible to detect. I'm going to wait for Hyprland 0.34 to appear on Arch before taking further steps.

**Comment by nergdron** [comment]
oooof yeah, that definitely feels like an upstream bug, not your issue. good diagnosis, thanks! I'll report back once the new release is available.

**Comment by nwg-piotr** [comment]
Yes. I have a fix to avoid crashes, but it won't allow to detect disable monitors on Hyprland. It's impossible with `hyprctl monitors`, and `wlr-rand` gives partially wrong results. I think I'll apply what I have and try to raise an issue on the Hyprland tracker.

**Comment by nwg-piotr** [comment]
Closed by accident. The commit above should prevent us from crashes, but won't allow to detect disabled monitors, as said above.

**Comment by kRHYME7** [comment]
> The crash itself is possible to avoid, but we have another issue: disabled DP monitors disappear from the output of hyprctl monitors (why?!)


Maybe I misread something did you mean ``` hyprctl monitor all ``` ?  

with all flag 
![image](https://github.com/nwg-piotr/nwg-displays/assets/53417443/74e5d3d1-cb42-4d7f-846b-9557bc705a60)


but with this dpmsstatus still is 1 but maybe we can compare what is with all and without all flag.

**Comment by nwg-piotr** [comment]
Yes, it will be worked on. I need to rewrite this party of code from scratch.

**Comment by kRHYME7** [comment]
Thanks!
