### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by thamma** [nwg-piotr/nwg-displays#44]
Hello,

I installed `nwg-displays` on my arch just now and upon launch was greeted with the message `wlr-randr package required, but not found, terminating.`. After installing `wlr-randr` the tool worked just fine.

From what I can see, it seems that `wlr-randr` should be included in the [package's dependencies list](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nwg-displays) to avoid future manual intervention.

Thanks for developing this tool,

Best

**Comment by thamma** [comment]
While reading the PKGBUILD, I should have spotted the line `
optdepends=('wlr-randr: for Hyprland support')` which fully justifies `wlr-randr` not being a dependency.

Oops, thanks still!

**Comment by nwg-piotr** [comment]
Some Archers are sensitive to dependencies that they don't use themselves, that's why. :D

**Comment by thamma** [comment]
Very fair. Hyprland is my first wayland compositor and I struggle to tell apart Hyprland and Wayland utilities and sometimes assume they are the same!
