### ISSUE TITLE
nwg-displays crashes when trying to open it after enabling mirrorring

### ISSUE THREAD

**Issue by emielvanseveren** [nwg-piotr/nwg-displays#61]
Mirroring 2 screens works (both directions). Resulting in the following config:

monitor=DP-1,1920x1080@143.85,3440x360,1.0,mirror,DP-2
monitor=DP-2,3440x1440@59.97,0x0,1.0

or

monitor=DP-1,1920x1080@143.85,3440x360,1.0
monitor=DP-2,3440x1440@59.97,0x0,1.0,mirror,DP-1

But when trying to open nwg-displays the following error appears:

ettings: {'view-scale': 0.15, 'snap-threshold': 10, 'indicator-timeout': 500, 'custom-mode': [], 'use-desc': False}
Running on Hyprland
Traceback (most recent call last):
  File "/usr/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.3.19', 'gui_scripts', 'nwg-displays')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_displays/main.py", line 1252, in main
    create_display_buttons()
  File "/usr/lib/python3.12/site-packages/nwg_displays/main.py", line 569, in create_display_buttons
    outputs = list_outputs()
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_displays/tools.py", line 183, in list_outputs
    outputs_dict[key]["monitor"] = monitors[idx]
                                   ~~~~~~~~^^^^^
IndexError: list index out of range

**Comment by nwg-piotr** [comment]
Which nwg-displays version are you on? This shouldn't happen on 0.3.20.

**Comment by emielvanseveren** [comment]
I was on 0.3.19. You're right, fixed in 0.3.20.
