### ISSUE TITLE
restore back to strange size

### ISSUE THREAD

**Issue by YWh0301** [nwg-piotr/nwg-displays#69]
my laptop has a 2560x1440 monitor. but everytime i open nwg-displays the defualt number in the size columns are some strange number 1925x1083. if i hit apply my screen would just go black.everytime i ditch my settings by clicking restore the size fallback to 1925x1083 too. Can it stay with my current config?

**Comment by nwg-piotr** [comment]
The program only knows what the compositor reports, either from the sway tree, or from `hyprctl monitors`.

**Comment by YWh0301** [comment]
this is my hyprctl monitors output:

> Monitor eDP-1 (ID 0):
	2560x1440@120.00000 at 0x0
	description: Thermotrex Corporation TL140BDXP01-0
	make: Thermotrex Corporation
	model: TL140BDXP01-0
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.33
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 2560x1440@120.00Hz 2560x1440@60.00Hz 1920x1200@120.00Hz 1920x1080@120.00Hz 1600x1200@120.00Hz 1680x1050@120.00Hz 1280x1024@120.00Hz 1440x900@120.00Hz 1280x800@120.00Hz 1280x720@120.00Hz 1024x768@120.00Hz 800x600@120.00Hz 640x480@120.00Hz 

im confused why it gets 1925x1083 tho.

**Comment by nwg-piotr** [comment]
I have a suspicion. The [latest PR](https://github.com/nwg-piotr/nwg-displays/pull/68) might've spoiled this. Which nwg-displays version are you on?

**Comment by YWh0301** [comment]
i used pacman to install it on arch today.its 0.3.20

> nwg-displays -v   
nwg-displays version 0.3.20

**Comment by nwg-piotr** [comment]
I'll revert the latest change. I should've checked it better.

**Comment by YWh0301** [comment]
thanks for such efficient response!

**Comment by nwg-piotr** [comment]
Well, it looks perfectly well on my side. My DP-1 is 2560 x 1440. When I set scale to 1.33, I still see proper width and height values. I'm a bit confused.

**Comment by nwg-piotr** [comment]
Could you list the `/usr/lib/python3.12/site-packages/nwg_displays-0.3.20-py3.12.egg/nwg_displays/tools.py` file and show me lines 138 - 142?

**Comment by nwg-piotr** [comment]
Got it. It seems we have a packaging error. What's provided with the Extra package contains the old code.

**Comment by nwg-piotr** [comment]
Got it. The code I use has not yet been released, stupid me! I'll make a release, and it should be fixed.

**Comment by nwg-piotr** [comment]
Fixed in v0.3.21.
