### ISSUE TITLE
GUI Scaling Issue with Multiple Monitors of Varying Resolutions

### ISSUE THREAD

**Issue by hakan-demirli** [nwg-piotr/nwg-displays#72]
I use multiple monitors/projectors throughout the day. Their resolutions varies from 4K to 480p. When I open nwg-displays while one of them is plugged in, the scale/zoom of the GUI becomes messed up. Scale/zoom does not change when I move nwg-displays from one monitor to the next. 

Reproduce:
* Have 1080p primary monitor.
* Connect another 1080p secondary monitor.
* Disconnect the secondary monitor.
* Connect 480p projector.
* Open nwg-displays
* Observe that `apply` button is not visible. You can not see below `Modes` due to resolution/DPI problem. It is also not possible to scroll the GUI when it is truncated.
* Move the nwg-displays to the primary monitor. It is still truncated.

**Workaround:** Delete all existing monitor configurations and try again.

**Comment by nwg-piotr** [comment]
Try changing zoom.

![obraz](https://github.com/user-attachments/assets/2c946190-d209-4781-9815-d0d627b17a8d)

![obraz](https://github.com/user-attachments/assets/da1af6f4-fa4f-4d4e-bcd4-32e900fccbe5)

**Comment by hakan-demirli** [comment]
Thank you. I can finally reach the apply button when I am using the projector.

I will close the issue since my problem is solved however if I set the Zoom to 0.5 and then plug the projector I cant even see the Zoom buttons. To solve this I have to:
* Unplug the projector
* Set zoom to 0.1
* Plug the projector back in

I assume this workaround will not work when the primary monitor of the user is 4K and external monitor is 480p since 480p is 16 times bigger than 4K and the zoom button only allows minimum of 10% of the primary resolution.
