### ISSUE TITLE
Bridging gap between screens of different DPI/resolutions

### ISSUE THREAD

**Issue by markusHaferkamp** [nwg-piotr/nwg-displays#73]
Hello Piotr,

Thank you for the work you've put into this project!

I've looked through all the documentation I could find, but I'm still stuck with a rather simple issue: How do I get the mouse to transition over a gap? e-DP1 is living a rather solitary life down there right now.

Can I somehow increase the distance NWG-Displays considers as directly adjacent? Scaling to equal size is sadly not an option, as it does tend to make things a bit blurry.

![image](https://github.com/user-attachments/assets/c170caa4-3a14-441d-bd7a-54338515efcf)

**Comment by nwg-piotr** [comment]
This has nothing to do with nwg-displays itself. We only draw symbolic images and export config files here. This is a compositor property.

**Comment by markusHaferkamp** [comment]
Thank you! Reckon I'll take a closer look at Sway's config files then! :)
